In [70]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd 

In [71]:
tesla = pd.read_csv("data/TSLA.csv")
tesla.drop(['Adj Close'], axis = 1)
trainingset = tesla.iloc[:,1:2].values


In [72]:
from sklearn.preprocessing import MinMaxScaler

In [73]:
mnmsc = MinMaxScaler(feature_range=(0,1))
trainingset_sc = mnmsc.fit_transform(trainingset)
X_train = []
y_train = []
for i in range(60, 1258):
    X_train.append(trainingset_sc[i-60:i, 0])
    y_train.append(trainingset_sc[i, 0])
X_train, y_train = np.array(X_train), np.array(y_train)

# Reshaping
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
print(X_train)


[[[0.00434948]
  [0.01467569]
  [0.01347426]
  ...
  [0.00688921]
  [0.00722379]
  [0.00719337]]

 [[0.01467569]
  [0.01347426]
  [0.01043267]
  ...
  [0.00722379]
  [0.00719337]
  [0.00570299]]

 [[0.01347426]
  [0.01043267]
  [0.00587028]
  ...
  [0.00719337]
  [0.00570299]
  [0.00579424]]

 ...

 [[0.25809445]
  [0.26977416]
  [0.26242871]
  ...
  [0.37451143]
  [0.37413124]
  [0.3713482 ]]

 [[0.26977416]
  [0.26242871]
  [0.26475553]
  ...
  [0.37413124]
  [0.3713482 ]
  [0.38147671]]

 [[0.26242871]
  [0.26475553]
  [0.27657212]
  ...
  [0.3713482 ]
  [0.38147671]
  [0.38067069]]]


In [74]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout


In [75]:
regressor = Sequential()
regressor.add(LSTM(units=100,return_sequences=True, input_shape = (X_train.shape[1],1)))
regressor.add(Dropout(0.2))
regressor.add(LSTM(units=100,return_sequences=True, input_shape = (X_train.shape[1],1)))
regressor.add(Dropout(0.2))
regressor.add(LSTM(units=100,return_sequences=True, input_shape = (X_train.shape[1],1)))
regressor.add(Dropout(0.2))

regressor.add(LSTM(units=100,return_sequences=True))
regressor.add(Dropout(0.2))
regressor.add(Dense(units = 1))

regressor.compile(optimizer='adam',loss='mean_squared_error')




In [76]:
regressor.fit(X_train,y_train,epochs = 100,batch_size = 32)

Epoch 1/100
38/38 [==============================] - 3s 90ms/step - loss: 0.0071
Epoch 2/100
38/38 [==============================] - 3s 79ms/step - loss: 0.0031
Epoch 3/100
38/38 [==============================] - 3s 78ms/step - loss: 0.0027
Epoch 4/100
38/38 [==============================] - 3s 78ms/step - loss: 0.0023
Epoch 5/100
38/38 [==============================] - 3s 79ms/step - loss: 0.0021
Epoch 6/100
38/38 [==============================] - 3s 78ms/step - loss: 0.0020
Epoch 7/100
38/38 [==============================] - 3s 79ms/step - loss: 0.0018
Epoch 8/100
38/38 [==============================] - 3s 77ms/step - loss: 0.0017
Epoch 9/100
38/38 [==============================] - 3s 78ms/step - loss: 0.0016
Epoch 10/100
38/38 [==============================] - 3s 78ms/step - loss: 0.0016
Epoch 11/100
38/38 [==============================] - 3s 77ms/step - loss: 0.0016
Epoch 12/100
38/38 [==============================] - 3s 77ms/step - loss: 0.0014
Epoch 13/100
38/38 [=====

In [97]:
tesla[0:1800].to_csv('data/training.csv')
tesla[1800:2100].to_csv('data/test.csv')

In [ ]:
dataset_test = tesla.iloc[:,2000:2145].values
real_stock_price = dataset_test[:, 1:2]

dataset_total = pd.concat((tesla['Open']),axis = 0)
inputs = dataset_total[len(dataset_total)- len(dataset_total) - 240].values

inputs = inputs.reshape(-1,1)
inputs = sc.transform(inputs)
X_test = []

for i in range(240,260):
    X_test.append(input[i-240:i,0])
X_test = np.array(X_test)
X_test = np.reshape(X_test,(X_test.shape[0],X_test.shape[1],1))

predicted_price = regressor.predict(X_test)
